# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# should work with older version of icd
# r_github_packages:
#  - jackwasey/icd
#  - jackwasey/icd@v3.4
