# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

matrix:
  allow_failures:
    - r: oldrel

r_packages:
  - covr

r_github_packages:
  - jimhester/lintr
#  - jimhester/covr
# should work with old and development versions of icd
#  - jackwasey/icd
#  - jackwasey/icd@v3.4

before_script:
 - rm .Rinstignore # do install everything for testing
 - sed -i'' '/.*[Dd]ata.*/d' .Rbuildignore # do include (raw) data for testing
 - sed -i'' '/\.covrignore/d' .Rbuildignore
 - sed -i'' '/\.lintr/d' .Rbuildignore

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
