# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

env:
  global:
    - ICD_DATA_VERBOSE=TRUE
    # travis uses --as-cran by default
    - _R_CHECK_EXIT_ON_FIRST_ERROR_=true

matrix:
  fast_finish: true
  allow_failures:
    - r: oldrel
    - env: ICD_DATA_OFFLINE=FALSE

r_packages:
  - httr

r_github_packages:
  - r-lib/covr

before_script:
  - sed -i'' '/.*[Dd]ata.*/d' .Rbuildignore # do include any (raw) data for testing

notifications:
  email:
    on_success: change
    on_failure: change

