# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: true

# should work with older version of icd
# r_github_packages:
#  - jackwasey/icd
#  - jackwasey/icd@v3.4

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/lintr
  - jimhester/covr

matrix:
  allow_failures:
    - r: oldrel

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
