# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

env:
  global:
    - ICD_DATA_INTERACT=FALSE
    - ICD_DATA_VERBOSE=TRUE
  matrix:
    - ICD_DATA_OFFLINE=TRUE
    - ICD_DATA_OFFLINE=FALSE
#   - R_CHECK_ARGS="--install-args=--no-staged-install"

matrix:
  fast_finish: true
  allow_failures:
    - r: oldrel
    - env: ICD_DATA_OFFLINE=FALSE

r_packages:
  - httr

r_github_packages:
#  - jimhester/lintr
  - jimhester/covr
  - jackwasey/icd

before_script:
 - sed -i'' '/.*[Dd]ata.*/d' .Rbuildignore # do include (raw) data for testing
# - sed -i'' '/\.covrignore/d' .Rbuildignore
# - sed -i'' '/\.lintr/d' .Rbuildignore
# otherwise, icd is installed from CRAN, and after the github install???
 - 'echo "Remotes: jackwasey/icd" >> DESCRIPTION'
 - 'echo "StagedInstall: no" >> DESCRIPTION'
 - cat DESCRIPTION

after_success:
  - R CMD INSTALL $PKG_TARBALL
#  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'if (!require("remotes")) {install.packages("remotes")}; remotes::install_github("jackwasey/icd")
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
