# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

icd10cm_compare_rcpp <- function(x, y) {
    .Call('_icd_data_icd10cmCompare', PACKAGE = 'icd.data', x, y)
}

icd10cm_sort_rcpp <- function(x) {
    .Call('_icd_data_icd10cmSort', PACKAGE = 'icd.data', x)
}

icd10cm_order_rcpp <- function(x) {
    .Call('_icd_data_icd10cmOrder', PACKAGE = 'icd.data', x)
}

